### ISSUE TITLE
Display Board Edit page after saving board settings

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#12]
After saving board settings, we end up in the board list view. This is cumbersome especially when the board is on the second page. Displaying the edit page might be more user friendly.

**Comment by oarchner** [comment]
Board list view is rendered with paging and group filter after saving the board.

**Comment by oarchner** [comment]
Not as simple as I thougt. Child controllers return no paging and group values.

**Comment by holzheu** [comment]
Tab navigation improved board editing. But still, when editing the board name first saving returns to the list. One has to find the board again to edit the channels. Just staying on the edit view with a "changes saved" alert would be more convenient.

**Comment by oarchner** [comment]
Save button -> Save data and stay on page
Ok button -> Save data and close page (used as default for scaffolding)
