### ISSUE TITLE
Tomcat response 404 not found to /gateway/

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#15]
Problem on bti3x7

<pre>
/etc/init.d/tomcat6 status
</pre>
gave tomcat running. Http-Access to /gateway/ however gave 404 not found. Here some logs:
<pre>
...
2015-06-02 08:26:12,443 INFO  de.unibayreuth.bayceer.bayeos.xmlrpc.handler.LogOffHandler.terminateSession  - Terminated session 1237506065 for userid 200502.
Jun 02, 2015 7:27:40 AM org.apache.catalina.core.StandardService stop
INFORMATION: Stopping service Catalina
2015-06-02 08:27:40,927 INFO  de.unibayreuth.bayceer.bayeos.xmlrpc.XMLServlet.destroy  - Destroying servlet XMLServlet ...
Jun 02, 2015 7:27:40 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SCHWERWIEGEND: The web application [/BayEOS-Server] registered the JDBC driver [org.postgresql.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Jun 02, 2015 7:27:40 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SCHWERWIEGEND: The web application [/BayEOS-Server] appears to have started a thread named [FileWatchdog] but has failed to stop it. This is very likely to create a memory leak.
Jun 02, 2015 8:27:49 AM org.apache.catalina.startup.Catalina load
INFORMATION: Initialization processed in 3542 ms
...
</pre>

**Comment by holzheu** [comment]
Seemed to be a postgres performance issue related to the exporter. delete_obs function failed to move observations to observations_exp resulting in the observation table to blow up...

Reimplementation of delete_obs improved delete performance. Will be included in 1.9.17 release.

<pre>
CREATE OR REPLACE FUNCTION delete_obs(ctime timestamp with time zone, maxid bigint)
  RETURNS void AS
$BODY$
declare
 cha record;
begin
 insert into observation_exp select o.* from observation o, channel_detail c
 where o.id<=maxid and c.db_series_id is not null
 and c.id=o.channel_id and (
   (c.i_name is null and o.result_time<ctime) or
   (c.i_name is not null and o.result_time< date_truncate(ctime, c.i_name::interval) )
 );

 delete from observation as o
 using channel_detail c
 where o.id<=maxid and c.db_series_id is not null
 and c.id=o.channel_id and (
   (c.i_name is null and o.result_time<ctime) or
   (c.i_name is not null and o.result_time< date_truncate(ctime, c.i_name::interval) )
 );

return;
end;$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;


</pre>

**Comment by oarchner** [comment]
Rolled out with 1.9.17
