### ISSUE TITLE
Nagios "value OK" when no min/max is given?

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#16]
When working with the gateway, some channels (e.g. cpu time) do not have reasonable min/max values for validation. However, in order to get the channel to "value OK" one has to add at least one min/max validation value. Would be more convenient to have the channel set to "value OK" automatically, when no min/max is given.

**Comment by oarchner** [comment]
Default changed from 'Missing Parameters' to 'Value ok'
