### ISSUE TITLE
Improve Chart-View  

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#18]
There is a time delay in selecting and deselecting channels. Is it possible to do this via jQuery in the browser? 

Additionally a "select/deselect all" checkbox in the table head would be great. 
Example for this see BayEOSViewer-> Chart -> ShowData

**Comment by oarchner** [comment]
* Removed time delay on load
* Added select all, deselect all button
* Selection triggers redraw()
