### ISSUE TITLE
Group View in Gateway?

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#22]
With 1.9.20 Group View of board seems to be broken!

http://bayeos.bayceer.uni-bayreuth.de/gateway/?group=BOD

**Comment by oarchner** [comment]
Wrong URL to show the group view. 

Valid URL for nagios group status: http://bayeos.bayceer.uni-bayreuth.de/gateway/nagios/group/BOD

Valid URL to show/edit group by id: http://bayeos.bayceer.uni-bayreuth.de/gateway/boardGroup/edit/1
