### ISSUE TITLE
Board list view

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#24]
Some feedback to the board list view:

1. Having the group as the first column does not seem does not seem very intuitive to me. I often want to get the board details and click on the group name.
2. Sorting via group name does not give stable board lists. Reloads often results in totally different view.

Putting the origin as first column may be a solution to both points.

**Comment by oarchner** [comment]
New list order:
Origin|Group|Name|Rssi|Last Result Time|Status
