### ISSUE TITLE
Implement "exclude critical values from export"

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#27]
# Background

Using RF24 it happens from time to time, that junk frames arrive at the gateway. Adding this frame with a junk value of 5027.84 to the normal temperature values of around 20, the 10 minute aggregation results in a spike:

![spike_rf24_temp](https://cloud.githubusercontent.com/assets/7067062/15669613/8b54acac-2721-11e6-821a-82b184cc39d8.png)
# Solution

Add a per channel/per board option "exclude critical values from export"

**Comment by oarchner** [comment]
Implemented in 2.3.0
