### ISSUE TITLE
Implement Checksum Frame

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#29]
To avoid invalid frames, frames can be wrapped in a checksum frame:
`[0xf][bayeos_frame][uint16_t checksum]`
Here the example code who the checksum is calcualted in the BayEOS Arduino lib:

<pre>
uint8_t BayEOS::addChecksum() {
    uint16_t checksum = 0;
    for (uint8_t i = 0; i < _next; i++) {
        checksum += _payload[i];
    }
    return addToPayload((uint16_t)(0xffff - checksum & 0xffff));
}
</pre> 

To validate a received checksum the following case was added to the PHP BayEOSGatewayClient-lib:

<pre>
            case 0xf:
                $checksum=0;
                $pos=0;
                while($pos < strlen($frame)-2){
                    $checksum += BayEOSType::unpackUINT8(substr($frame,$pos,1));
                    $pos++;
                }
                $checksum += BayEOSType::unpackUINT16(substr($frame,$pos,2));
                
                $validChecksum=($checksum==0xffff);
                return BayEOS::parseFrame(substr($frame,1,-2),$ts,$origin,$rssi,$validChecksum);
                break;

</pre> 

Checksum frames with invalid checksums should be discarded in the gateway.

**Comment by oarchner** [comment]
Frame type 0xf added.
Gateway FrameService catches InvalidChecksum exceptions.
