### ISSUE TITLE
Export origin into description of measurement folder

### ISSUE THREAD

**Issue by holzheu** [BayCEER/bayeos-gateway#30]
The gateway exporter creates a measurement folder for each board. The name of the folder is taken from the board name. Board origin gets lost. Would be good the automatically add a description like
"Create by Gateway ($GATEWAY_URL$), Board ($ORIGIN$)"

**Comment by oarchner** [comment]
![clipboard02](https://cloud.githubusercontent.com/assets/5363999/20790618/639150b6-b7b9-11e6-8d07-6bc237372c04.jpg)

Implemented in 1.9.36
