### ISSUE TITLE
Enhanced Syncing of Objects between Gateway and Server 

### ISSUE THREAD

**Issue by oarchner** [BayCEER/bayeos-gateway#33]
__Problem:__
The current sync procedure lacks the correct handling of server side deletion of objects

__Background:__
The following objects are synced between gateway and server during the gateway export procedure:

| Gateway | Server |
| --------- | ------- |
|Board Group|Folder 
|Board|Folder
|Channel|Measurement Series
|Unit|Unit

Each mapped object on the gateway has a db_id attribute.

__Current Sync Procedure__
```python
if object should be synced:
    if object.db_id is null 
     id = create new server object 
     update object.db_id
    end if
end if
``` 

__Improved Sync Procedur including validation check on objects__
```python
if object should be synced:
    if object.db_id is null or object.db_id is not valid: 
     id = create new server object 
     update object.db_id
    end if
end if
```

**Comment by holzheu** [comment]
Board Group has to be handled differently:

If folder is deleted on server set db_id on gateway to null for board group.

**Comment by oarchner** [comment]
Refactored [exporter](src/main/java/de/unibayreuth/bayceer/bayeos/gateway/service/ExportObsJob.groovy) has a hierachical fallback strategy to fix syncing problems.
